---
- name: stop gateways
  when: item.state == "stopped"
  block:
    - name: stop gateway vms
      proxmox_kvm:
        api_user: root@pam
        api_password: "{{ pve_credentials.api_password }}"
        api_host: "{{ pve_nodes[0] }}"
        name: "{{ item.uuid }}-{{ idx + 1}}"
        state: stopped
      loop: "{{ item.nodes }}"
      loop_control:
        loop_var: _item
        index_var: idx


- name: remove gateway, and ceph auth keys
  when: item.state == "absent" or item.state == "purged"
  block:
    - name: destroy vms with terraform
      shell: terraform destroy --auto-approve --target proxmox_vm_qemu.{{ item.uuid }}-gw-{{ idx + 1 }}
      args:
        chdir: /opt/vm-config/terraform
      loop: "{{ item.nodes }}"
      loop_control:
        loop_var: _item
        index_var: idx

    - name: destroy terraform plan locally stored
      file:
        path: "/opt/vm-config/terraform/{{ item.uuid }}.tf"
        state: absent    

    - name: remove locally stored ssh keys on sysmgr
      file:
        path: "{{ _item }}"
        state: absent
      loop:
        - /opt/vm-config/ssh/{{ item.uuid }}
        - /opt/vm-config/ssh/{{ item.uuid }}.pub
      loop_control:
        loop_var: _item

    - name: remove ceph key from monitors
      command: "ceph auth del client.{{ item.uuid }}"
      delegate_to: "{{ groups.mons[0] }}"

    - name: remove ceph key/secret locally stored on sysmgr
      file:
        path: "/opt/vm-config/ceph/{{ item.uuid }}"
        state: absent

